apiVersion: v1
kind: Service
metadata:
  name: broker-service
  namespace: ai-service
spec:
  type: NodePort  # 👈 NodePort로 변경
  selector:
    app: broker-server
  ports:
    - protocol: TCP
      port: 9000      # 서비스 내부 포트
      targetPort: 9000 # 컨테이너 포트
      nodePort: 30001  # 👈 외부(윈도우/Proxmox)에서 접속할 포트
