# /etc/sysctl.d/99-performance.conf

# 1. 대기 열(Backlog) 크기 최대화
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 65535

# 2. 들어오는 패킷을 처리하는 CPU 큐 확장
net.core.netdev_max_backlog = 65535

# 3. 소켓 장부(Bucket) 크기 확장
net.ipv4.tcp_max_tw_buckets = 2000000

# 4. 메모리 부족 시 연결 요청 대응
net.ipv4.tcp_syncookies = 1

# 5. 메모리 맵(Memory Map) 개수 확장 (Kafka/DB 최적화)
vm.max_map_count = 262144
